# Generated by Django 3.2.7 on 2021-11-29 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moments', '0002_person_personimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='例如：新宿事件', max_length=20, verbose_name='事件名称')),
                ('event_num', models.CharField(help_text='例如：20211121-1', max_length=10, verbose_name='专题编号')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('discription', models.CharField(help_text='例如：', max_length=220, verbose_name='专题描述')),
                ('note', models.TextField(help_text='按照书本一点不差的即兴发挥吧', max_length=1000, verbose_name='记录')),
                ('cover_image', models.ImageField(blank=True, help_text='专题封面', upload_to='moments_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='moments_pics')),
                ('story', models.TextField(help_text='写下那些故事吧', null=True, verbose_name='故事')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moments.event')),
            ],
            options={
                'verbose_name': '专题图片集',
                'verbose_name_plural': '专题图片集',
            },
        ),
    ]
