# Generated by Django 3.2.7 on 2022-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_rename_person_eventimage_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': '事件图片集', 'verbose_name_plural': '事件图片集'},
        ),
        migrations.AlterModelOptions(
            name='personimage',
            options={'verbose_name': '人物图片集', 'verbose_name_plural': '人物图片集'},
        ),
    ]
