# Generated by Django 3.2.7 on 2022-05-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0005_auto_20220102_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '专题图片集', 'verbose_name_plural': '专题图片集'},
        ),
        migrations.AlterModelOptions(
            name='collectionimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '事件图片集', 'verbose_name_plural': '事件图片集'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '人物图片集', 'verbose_name_plural': '人物图片集'},
        ),
        migrations.AlterModelOptions(
            name='personimage',
            options={},
        ),
    ]
