# Generated by Django 3.2.7 on 2023-03-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0006_auto_20220528_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(help_text='例如：时空漫步者，15字以内', max_length=20, verbose_name='专题名称'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='discription',
            field=models.CharField(help_text='例如：浔阳江头夜送客，枫叶荻花秋瑟瑟...', max_length=220, verbose_name='专题描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='discription',
            field=models.CharField(help_text='例如：永和九年，岁在癸丑，暮春之初...', max_length=220, verbose_name='专题描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='例如：新宿事件，15字以内', max_length=20, verbose_name='事件名称'),
        ),
        migrations.AlterField(
            model_name='person',
            name='discription',
            field=models.CharField(help_text='例如：一位粉妆玉砌，傲骨英风的翩翩少年', max_length=220, verbose_name='专题描述'),
        ),
    ]
