# Generated by Django 3.2.7 on 2023-03-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(help_text='项目进展更新', null=True, verbose_name='故事')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
        ),
    ]
