# Generated by Django 3.2.7 on 2021-10-21 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=20)),
                ('flight_num', models.CharField(max_length=10)),
                ('flight_date', models.DateField(auto_now_add=True)),
                ('takeoff_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrive_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('provenance', models.TextField(max_length=50)),
                ('destination', models.TextField(max_length=50)),
                ('note', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
