# Generated by Django 3.2.7 on 2021-10-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20211025_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='picture',
        ),
    ]
