# Generated by Django 3.2.7 on 2021-10-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_lane_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='', upload_to='lane_pics')),
                ('lane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.lane')),
            ],
        ),
    ]
