# Generated by Django 3.2.7 on 2021-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='picture',
            field=models.ImageField(default='', upload_to='lane_pics'),
        ),
    ]
