# Generated by Django 3.2.7 on 2021-10-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_rename_lane_flash_lane_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flash',
            old_name='lane_id',
            new_name='hook',
        ),
    ]
