# Generated by Django 3.2.7 on 2021-10-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_rename_lane_id_flash_hook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flash',
            old_name='hook',
            new_name='lane',
        ),
    ]
