# Generated by Django 3.2.7 on 2021-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_rename_hook_flash_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='picture',
            field=models.ImageField(default='', upload_to='flash_pics'),
        ),
    ]
