# Generated by Django 3.2.7 on 2021-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_alter_flash_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='flash_pics'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='lane_pics'),
        ),
    ]
