# Generated by Django 3.2.7 on 2021-10-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_flash_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='lane',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='flight.lane'),
            preserve_default=False,
        ),
    ]
