# Generated by Django 3.2.7 on 2021-10-30 08:23

from django.db import migrations, models
import flight.models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_alter_flash_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='lane',
            field=models.ForeignKey(on_delete=models.SET(flight.models.get_flash_id), to='flight.lane'),
        ),
    ]
