# Generated by Django 3.2.7 on 2021-10-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_alter_flash_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight.lane'),
        ),
    ]
