# Generated by Django 3.2.7 on 2021-10-30 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0016_alter_flash_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='story',
            field=models.TextField(help_text='写下那些故事吧', null=True, verbose_name='故事'),
        ),
        migrations.AlterField(
            model_name='flash',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='destination',
            field=models.CharField(max_length=10, verbose_name='到达地点'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='flight_date',
            field=models.DateField(auto_now_add=True, verbose_name='航班日期'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='flight_name',
            field=models.CharField(max_length=20, verbose_name='航空公司'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='flight_num',
            field=models.CharField(max_length=10, verbose_name='航班名称'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='note',
            field=models.TextField(max_length=1000, verbose_name='记录'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='provenance',
            field=models.CharField(max_length=10, verbose_name='出发地点'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='takeoff_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='起飞时间'),
        ),
    ]
