# Generated by Django 3.2.7 on 2021-10-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0017_auto_20211030_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flash',
            options={'verbose_name': '那些回忆', 'verbose_name_plural': '那些回忆'},
        ),
    ]
