# Generated by Django 3.2.7 on 2021-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0018_alter_flash_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='destination',
            field=models.CharField(help_text='例如：上海虹桥机场T1航站楼', max_length=10, verbose_name='到达地点'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='flight_name',
            field=models.CharField(help_text='例如：成都航空', max_length=20, verbose_name='航空公司'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='flight_num',
            field=models.CharField(help_text='例如：ZH7847', max_length=10, verbose_name='航班名称'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='note',
            field=models.TextField(help_text='按照书本一点不差的即兴发挥吧', max_length=1000, verbose_name='记录'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='provenance',
            field=models.CharField(help_text='例如：成都双流机场T2航站楼', max_length=10, verbose_name='出发地点'),
        ),
    ]
