# Generated by Django 3.2.7 on 2021-11-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0019_auto_20211108_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flash',
            options={'verbose_name': 'flashes', 'verbose_name_plural': 'flashes'},
        ),
    ]
