# Generated by Django 3.2.7 on 2021-11-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0020_alter_flash_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='lane',
            field=models.ForeignKey(default=None, help_text='对应行程', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.lane'),
        ),
    ]
