# Generated by Django 3.2.7 on 2021-11-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0022_laneimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flash',
            options={'verbose_name': 'flashs', 'verbose_name_plural': 'flashs'},
        ),
    ]
