# Generated by Django 3.2.7 on 2021-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_status',
            field=models.ManyToManyField(to='plans.PlanStatus'),
        ),
    ]
