# Generated by Django 3.2.7 on 2021-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20211124_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanStatus',
            new_name='PlanTag',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_state',
            field=models.IntegerField(null=True, verbose_name='任务状态'),
        ),
    ]
