# Generated by Django 3.2.7 on 2021-11-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_plan_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_status',
        ),
    ]
