# Generated by Django 3.2.7 on 2021-11-26 14:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('plans', '0005_remove_plan_plan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
