# Generated by Django 3.2.7 on 2021-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211030_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='重要的细节及逻辑', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='言简意赅的表述大意即可', max_length=100, verbose_name='标题'),
        ),
    ]
