# Generated by Django 3.2.7 on 2022-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='story',
            field=models.TextField(help_text='写下那些故事吧', null=True, verbose_name='故事'),
        ),
    ]
