# Generated by Django 3.2.7 on 2021-10-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penny',
            new_name='Stiver',
        ),
    ]
