# Generated by Django 3.2.7 on 2021-10-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penny', '0002_rename_penny_stiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='stiver',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='作者'),
            preserve_default=False,
        ),
    ]
