# Generated by Django 3.2.7 on 2021-10-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0003_stiver_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='stiver',
            name='note',
            field=models.TextField(max_length=1000, null=True, verbose_name='记录'),
        ),
    ]
