# Generated by Django 3.2.7 on 2021-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0004_stiver_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiver',
            name='money',
            field=models.FloatField(null=True, verbose_name='金额'),
        ),
    ]
