# Generated by Django 3.2.7 on 2022-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0005_alter_stiver_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('account_type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Foreign'), (3, 'System')], default=1)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show_on_dashboard', models.BooleanField(default=False)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('import_ibans', models.TextField(default='[]')),
                ('import_names', models.TextField(default='[]')),
            ],
            options={
                'ordering': ['-active', 'name'],
                'unique_together': {('name', 'account_type')},
            },
        ),
    ]
