# Generated by Django 3.2.7 on 2021-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('picture', models.ImageField(blank=True, help_text='待解析图片', upload_to='health_pics')),
            ],
        ),
    ]
