# Generated by Django 3.2.7 on 2021-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='breath_score',
            field=models.CharField(max_length=10, null=True, verbose_name='呼吸质量'),
        ),
        migrations.AddField(
            model_name='record',
            name='deep_time',
            field=models.CharField(max_length=10, null=True, verbose_name='深睡时长'),
        ),
        migrations.AddField(
            model_name='record',
            name='dream_time',
            field=models.CharField(max_length=10, null=True, verbose_name='做梦时长'),
        ),
        migrations.AddField(
            model_name='record',
            name='get_bed_time',
            field=models.CharField(max_length=10, null=True, verbose_name='入睡时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='get_up_time',
            field=models.CharField(max_length=10, null=True, verbose_name='苏醒时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='light_time',
            field=models.CharField(max_length=10, null=True, verbose_name='浅睡时长'),
        ),
        migrations.AddField(
            model_name='record',
            name='score',
            field=models.CharField(max_length=10, null=True, verbose_name='睡眠分数'),
        ),
        migrations.AddField(
            model_name='record',
            name='snap_time',
            field=models.CharField(max_length=10, null=True, verbose_name='零星小睡'),
        ),
        migrations.AddField(
            model_name='record',
            name='sober_time',
            field=models.CharField(max_length=10, null=True, verbose_name='清醒时长'),
        ),
        migrations.AddField(
            model_name='record',
            name='total_time',
            field=models.CharField(max_length=10, null=True, verbose_name='总睡眠时长'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='日期'),
        ),
    ]
