# Generated by Django 3.2.7 on 2021-11-24 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_record_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
    ]
